# Generated by Django 3.1.3 on 2020-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201112_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Code', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='UserName',
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Year_of_study',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='RollNo',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Teacher_code', models.IntegerField(max_length=10, null=True)),
                ('Email', models.EmailField(max_length=30, null=True)),
                ('Special', models.TextField()),
                ('Courses_enrolled', models.ManyToManyField(to='base.Course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Courses_enrolled',
            field=models.ManyToManyField(to='base.Course'),
        ),
    ]
