# Generated by Django 3.1.3 on 2020-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201112_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Coordinator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
