# Generated by Django 3.1.3 on 2020-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201113_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_code',
            field=models.IntegerField(null=True),
        ),
    ]
