# Generated by Django 3.1.3 on 2020-11-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201113_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='UserName',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='UserName',
        ),
    ]
