# Generated by Django 3.1.3 on 2020-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20201114_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
