# Generated by Django 3.1.3 on 2020-11-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20201117_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Coursesenrolled',
            new_name='CoursesEnrolled',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Coursesenrolled',
            new_name='TeachedCourses',
        ),
    ]
