# Generated by Django 3.1.3 on 2020-11-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201117_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
