# Generated by Django 3.1.3 on 2020-11-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20201117_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CoursesEnrolled',
            field=models.ManyToManyField(to='base.Course'),
        ),
    ]
