# Generated by Django 3.1.3 on 2020-11-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_student_coursesenrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='TeachedCourses',
        ),
    ]
