# Generated by Django 3.1.3 on 2020-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_teacher_teachedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='TeachedCourses',
            field=models.ManyToManyField(to='base.Course'),
        ),
    ]
