# Generated by Django 3.1.3 on 2020-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20201117_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='CoursesEnrolled',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='CoursesEnrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='studentcourse',
            field=models.ManyToManyField(to='base.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachercourse',
            field=models.ManyToManyField(to='base.Teacher'),
        ),
    ]
