# Generated by Django 3.1.3 on 2020-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20201117_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='studentcourse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachercourse',
        ),
        migrations.AddField(
            model_name='student',
            name='CoursesEnrolled',
            field=models.ManyToManyField(to='base.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='CoursesEnrolled',
            field=models.ManyToManyField(to='base.Course'),
        ),
    ]
