# Generated by Django 3.1.3 on 2020-11-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_color_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='color_course',
            new_name='colorcourse',
        ),
    ]
