# Generated by Django 3.1.3 on 2020-11-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20201118_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
