# Generated by Django 3.1.3 on 2020-11-18 19:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20201119_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
        migrations.DeleteModel(
            name='colorcourse',
        ),
    ]
