# Generated by Django 3.1.3 on 2020-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20201119_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Department',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
