# Generated by Django 3.1.3 on 2020-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher_code',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
