# Generated by Django 3.1.3 on 2020-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20201119_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='UserName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
