# Generated by Django 3.1.3 on 2020-12-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20201204_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
