# Generated by Django 3.1.3 on 2020-12-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
