# Generated by Django 3.1.3 on 2020-12-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20201205_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
